name: mineswiper
description: Puzzle made with Flutter
version: 0.0.001+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  fluent_ui: ^3.9.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  gap: ^2.0.0
  go_router: ^0.0.1
  google_fonts: ^2.3.1
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0
  throttling: ^1.0.0

dev_dependencies:
  analyzer: ^3.2.0
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
